---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sweetrpg-game-room

resources:
    - ../../base
    - configmaps.yaml
    - ingress.yaml
    - middlewares/errors.yaml
    - middlewares/strip.yaml
    - pod-monitor.yaml
    - secrets/auth.yaml
    - secrets/cache.yaml
    - secrets/misc.yaml

labels:
    - pairs:
        app: web
        version: v1
        platform: sweetrpg
        package: game-room
        component: web

generatorOptions:
    disableNameSuffixHash: true
