---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sweetrpg-game-room

resources:
    - ../../base
    - configmaps.yaml
    - secrets.yaml
    - pod-monitor.yaml

labels:
    - pairs:
        app: web
        version: v1
        platform: sweetrpg
        package: game-room
        component: web

generatorOptions:
    disableNameSuffixHash: true
