---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sweetrpg-library

resources:
    - namespace.yaml
    - ../../base
    - configmaps.yaml
patchesStrategicMerge:
    - replicas.yaml

commonLabels:
    platform: sweetrpg
    app: sweetrpg-library-web-v1
    package: library
    component: web
    version: v1

generatorOptions:
    disableNameSuffixHash: true
