---
apiVersion: policy/v1
kind: PodDisruptionBudget

metadata:
    name: web-v1

spec:
    minAvailable: 1
    selector:
        matchLabels:
            app: web
            version: v1
            platform: sweetrpg
            package: library
            component: web
