---
apiVersion: external-secrets.io/v1beta1
kind: ClusterExternalSecret

metadata:
    name: web-v1-auth
    namespace: sweetrpg-library

spec:
    externalSecretName: web-v1-auth

    namespaceSelector:
        matchLabels:
            name: sweetrpg-library

    refreshTime: 1m

    externalSecretSpec:
        refreshInterval: "1h"
        secretStoreRef:
            name: akeyless
            kind: ClusterSecretStore
        target:
            name: web-v1-auth
            creationPolicy: Owner
        dataFrom:
            - extract:
                  key: Auth0

---
apiVersion: external-secrets.io/v1beta1
kind: ClusterExternalSecret

metadata:
    name: web-v1-misc
    namespace: sweetrpg-library

spec:
    externalSecretName: web-v1-misc

    namespaceSelector:
        matchLabels:
            name: sweetrpg-library

    refreshTime: 1m

    externalSecretSpec:
        refreshInterval: 1h
        secretStoreRef:
            name: akeyless
            kind: ClusterSecretStore
        target:
            name: web-v1-misc
            creationPolicy: Owner
        dataFrom:
            - extract:
                  key: /sweetrpg/library/web/misc

---
apiVersion: external-secrets.io/v1beta1
kind: ClusterExternalSecret

metadata:
    name: web-v1-cache
    namespace: sweetrpg-library

spec:
    externalSecretName: web-v1-cache

    namespaceSelector:
        matchLabels:
            name: sweetrpg-library

    refreshTime: 1m

    externalSecretSpec:
        refreshInterval: 1h
        secretStoreRef:
            name: akeyless
            kind: ClusterSecretStore
        target:
            name: web-v1-cache
            creationPolicy: Owner
        dataFrom:
            - extract:
                  key: /sweetrpg/library/web/cache
