---
apiVersion: external-secrets.io/v1
kind: ExternalSecret

metadata:
    name: game-room-web-cache

spec:
    refreshInterval: 1h
    secretStoreRef:
        name: akeyless
        kind: ClusterSecretStore
    target:
        name: web-cache
        creationPolicy: Owner
    dataFrom:
        - extract:
              key: /sweetrpg/support/cache/client
