---
apiVersion: apps/v1
kind: Deployment

metadata:
    name: web-v1

spec:
    replicas: 1
    strategy:
        rollingUpdate:
            maxSurge: 1
            maxUnavailable: 1
        type: RollingUpdate
    selector:
        matchLabels:
            app: library-web
            version: v1
            platform: sweetrpg
            package: library
            component: web
    template:
        metadata:
            labels:
                app: library-web
                version: v1
                platform: sweetrpg
                package: library
                component: web
        spec:
            serviceAccountName: library-web
            imagePullSecrets:
                - name: sweetrpg-registry
            initContainers:
                - name: init-templates
                  image: alpine/git
                  args:
                      - clone
                      - "--single-branch"
                      - "--"
                      - "https://$(GIT_USERNAME):$(GIT_PASSWORD)@github.com/$(GIT_REPO).git"
                      - "/work/."
                  envFrom:
                      - secretRef:
                            name: template-credentials
                  volumeMounts:
                      - mountPath: /work
                        name: templates
            containers:
                - name: app
                  image: ghcr.io/sweetrpg/library-web:latest
                  imagePullPolicy: Always
                  envFrom:
                      - configMapRef:
                            name: web-common
                      - configMapRef:
                            name: web-env
                      - secretRef:
                            name: web-v1-auth
                      - secretRef:
                            name: web-v1-misc
                      - secretRef:
                            name: web-v1-cache
                  env: []
                  ports:
                      - containerPort: 8282
                        name: http
                  resources:
                      requests:
                          cpu: "20m"
                          memory: "55m"
                      limits:
                          cpu: "1.0"
                          memory: "1Gi"
                  livenessProbe:
                      httpGet:
                          path: /health/ping
                          port: 8282
                      initialDelaySeconds: 90
                      timeoutSeconds: 10
                  readinessProbe:
                      httpGet:
                          path: /health/ping
                          port: 8282
                      initialDelaySeconds: 30
                      timeoutSeconds: 10
                  volumeMounts:
                      - mountPath: /data
                        name: data
                      - mountPath: /config
                        name: config
                      - mountPath: /app/templates
                        name: templates
                        subPath: templates
            volumes:
                - name: config
                  secret:
                      secretName: web-v1-files
                      items:
                          - key: newrelic.ini
                            path: newrelic.ini
                - name: data
                  emptyDir: {}
                - name: templates
                  emptyDir: {}
            restartPolicy: Always
