---
kind: Service
apiVersion: v1

metadata:
  name: sweetrpg-library-web

spec:
  selector:
    app: sweetrpg-library-web
  type: LoadBalancer
  ports:
    - name: http
      port: 8280
      targetPort: http
