---
kind: Service
apiVersion: v1

metadata:
  name: sweetrpg-library-web

spec:
  selector:
    app: sweetrpg-library-web
  type: LoadBalancer
  ports:
    - name: web
      port: 8080
      targetPort: web
