# -*- coding: utf-8 -*-
__author__ = "Paul Schifferer <dm@sweetrpg.com>"
"""constants.py
Constants for keys and environment variable names
"""

AUTH0_CLIENT_ID = "AUTH0_CLIENT_ID"
AUTH0_CLIENT_SECRET = "AUTH0_CLIENT_SECRET"
AUTH0_CALLBACK_URL = "AUTH0_CALLBACK_URL"
AUTH0_DOMAIN = "AUTH0_DOMAIN"
AUTH0_AUDIENCE = "AUTH0_AUDIENCE"
AUTH0_LOGIN_URL = "AUTH0_LOGIN_URL"

KANKA_CLIENT_ID = "KANKA_CLIENT_ID"
KANKA_CLIENT_SECRET = "KANKA_CLIENT_SECRET"
KANKA_CALLBACK_URL = "KANKA_CALLBACK_URL"
KANKA_DOMAIN = "KANKA_DOMAIN"
KANKA_AUDIENCE = "KANKA_AUDIENCE"

SENTRY_DSN = "SENTRY_DSN"
SENTRY_ENV = "SENTRY_ENV"

APPLICATION_NAME = "sweetrpg-game-room-web"
PROFILE_KEY = "profile"
JWT_PAYLOAD = "jwt_payload"
CURRENT_USER_ID = "current_user_id"
SESSION_ACCESS_TOKEN = "access_token"
SESSION_EMAIL = "email"
SESSION_USER_ID = "user_id"
SESSION_NAME = "name"
SESSION_ROLES = "roles"

# global keys
SWEETRPG_API_CLIENT_KEY = "sweetrpg-api-client"
ADMIN_API_CLIENT_KEY = "admin-api-client"
GAME_ROOM_CLIENT_KEY = "game-room-client"
CATALOG_CLIENT_KEY = "catalog-client"

# Visibility levels, ordered least to most exposed - matches game-room-objects' visibility enum
# (openspec/changes/shelf-service/specs/game-room-visibility).
VISIBILITY_LEVELS = ["private", "friends", "friends-of-friends", "public"]

# cookies
SWEETRPG_AUTH_KEY = 'sweetrpg-auth'

# Configuration
SEGMENT_WRITE_KEY = "SEGMENT_WRITE_KEY"
DEBUG = "DEBUG"
PORT = "PORT"
LOG_LEVEL = "LOG_LEVEL"
DB_HOST = "DB_HOST"
DB_PORT = "DB_PORT"
DB_USER = "DB_USER"
DB_PW = "DB_PW"
DB_NAME = "DB_NAME"
DB_OPTS = "DB_OPTS"
REDIS_HOST = "REDIS_HOST"
REDIS_PORT = "REDIS_PORT"
REDIS_DB = "REDIS_DB"
REDIS_PASS = "REDIS_PASS"
LOGSTASH_HOST = "LOGSTASH_HOST"
LOGSTASH_DB_PATH = "LOGSTASH_DB_PATH"
LOGSTASH_TRANSPORT = "LOGSTASH_TRANSPORT"
LOGSTASH_PORT = "LOGSTASH_PORT"

GAME_ROOM_API_BASE_URL = 'GAME_ROOM_API_BASE_URL'
APPLICATION_BASE_PATH = 'APPLICATION_BASE_PATH'
ADMIN_API_URL = 'ADMIN_API_URL'
CATALOG_API_URL = 'CATALOG_API_URL'
SHARED_URL = 'SHARED_URL'
CATALOG_WEB_URL = 'CATALOG_WEB_URL'
BUILD_INFO_PATH = 'BUILD_INFO_PATH'

SHARED_SESSION_REDIS_HOST = 'SHARED_SESSION_REDIS_HOST'
SHARED_SESSION_REDIS_PORT = 'SHARED_SESSION_REDIS_PORT'
SHARED_SESSION_REDIS_DB = 'SHARED_SESSION_REDIS_DB'
SHARED_SESSION_REDIS_PASS = 'SHARED_SESSION_REDIS_PASS'
