__author__ = "Paul Schifferer <dm@sweetrpg.com>"
"""
"""


FLAG_TRACKED_ENCOUNTER = 'tracked'
FLAG_REMOVED = 'removed'


ENUM_ORDERING_HIGH_TO_LOW = 'high-to-low'
ENUM_ORDERING_LOW_TO_HIGH = 'low-to-high'
ENUM_ORDERING_PCVADVERSARY = 'pc-v-adversary'
ENUM_ORDERING_PLAYER_MANAGED = 'player-managed'

ENUM_TIE_BREAKER_QUERY = 'query'
ENUM_TIE_BREAKER_RANDOM = 'random'
ENUM_TIE_BREAKER_ALPHA = 'alpha'

ENUM_IDENTITY_SOURCE_GITHUB = 'github'
ENUM_IDENTITY_SOURCE_WORDPRESS = 'wordpress'
ENUM_IDENTITY_SOURCE_TWITTER = 'twitter'
ENUM_IDENTITY_SOURCE_AMAZON = 'amazon'
ENUM_IDENTITY_SOURCE_LINKEDIN = 'linkedin'
ENUM_IDENTITY_SOURCE_GOOGLE = 'google-oauth2'
ENUM_IDENTITY_SOURCE_DB = 'db'
ENUM_IDENTITY_SOURCE_EMAIL = 'email'
ENUM_IDENTITY_SOURCE_SMS = 'sms'
ENUM_IDENTITY_SOURCE_SYSTEM = 'system'
ENUM_IDENTITY_SOURCE_KANKA = 'kanka'


PARTICIPANT_SCHEME = "participant"


ROLE_ADMIN = 'admin'
ROLE_USER = 'user'


ENTITLEMENT_GAME_SYSTEMS = 'game_systems'
