---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sweetrpg-library

resources:
  - namespace.yaml
  - ../../base
  - configmaps.yaml
  - ingress.yaml
secretGenerator:
  - name: sweetrpg-registry
    type: kubernetes.io/dockerconfigjson
    files:
      - .dockerconfigjson

commonLabels:
  app: sweetrpg-library-web

generatorOptions:
  disableNameSuffixHash: true
